### ISSUE TITLE
Min SDK version

### ISSUE THREAD

**Issue by GokhanArik** [donfuxx/Mockinizer#15]
Hi,

Is there any reason to keep minSdkVersion at 21? I think it could be lowered to 16 so more people can use it.

**Comment by donfuxx** [comment]
True, the min sdk version could be lower. The only reason why it's 21 atm is because it's the preselected value when creating a new project in Android Studio :smiley: 

Feel free to add a Pull request for this and I'll add it in next release.

**Comment by GokhanArik** [comment]
I will see if I can do it. I tried locally with Android 4 and ran into some issues. OkHttp doesn't support pre 21 anymore. They have a dedicated 3.12.x branch for Android 4, and it gave me TLS and certificate issues.

**Comment by donfuxx** [comment]
Yeah looks like [okhttp has now minSdk 21] (https://github.com/square/okhttp/blob/3d95c4b1f7d7631efe9273292aa74244b69aa008/android-test/build.gradle) set in their android tests. So probably it's a good idea to leave minSdk 21 for Mockinizer as well. 
Thx for investigating this though :-)
