### ISSUE TITLE
Allow mocking without having to specify a body

### ISSUE THREAD

**Issue by JuBan1** [donfuxx/Mockinizer#16]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to mock a `login` POST request that takes a `username` and `password` and returns some token.
But if I understand the workings of Mockinizer correctly, I can only mock that request if I provide a body (e.g. a username and password) in the RequestFilter. If I don't, the body of the RequestFilter will never be equal to the body of the actual request, thus the call never never be mocked.

However, that makes it practically unusable for something like a `login` request since the user can enter any name and password they wish.

**Describe the solution you'd like**
An option to make Mockinizer ignore the request body (such as `body = BODY.ANY`) in order to catch all requests made to that endpoint would be great.
Even better if Mockinizer were clever enough to find better matches if they exist and fall back to a `BODY.ANY` RequestFilter.

Thank you for this library. It's convenient and simple. For now I'll work around this issue by explicitly setting username and password to predefined values.

**Comment by donfuxx** [comment]
Hi @JuBan1 

Thx for your detailed feature request and for using Mockinizer! I think adding the possibility to allow to filter by any body would be very useful. Let me think about that.

cheers,

**Comment by donfuxx** [comment]
@JuBan1  This should be possible to do now in release https://github.com/donfuxx/Mockinizer/releases/tag/1.2.0 :+1: 

Example usage:

```
RequestFilter(
        path = "/typicode/demo/foo",
        method = Method.POST,
        body = null
    ) to MockResponse().apply {
        setResponseCode(200)
        setBody("""{"title":"I don't care which body you posted!"}""")
    }
```

Let me know if there are any issues with it

**Comment by JuBan1** [comment]
Sorry for the late response, we've had to put aside the project for a while.

I appreciate the update, and I've got it working on my end. Thanks.
