### ISSUE TITLE
Mockinizer not working with UI Tests using OkHttpIdlingResourceRule

### ISSUE THREAD

**Issue by kkl260** [donfuxx/Mockinizer#20]
**Describe the bug**
I have UI tests and I use OkHttpIdlingResourceRule() as a rule for my tests. The tests either don't use the mocks or terminates depending on how I set it up.

**To Reproduce**
My Retrofit Client 
`    

    @Provides
    @Reusable
    @JvmStatic
    internal fun provideRetrofitInterface(): Retrofit {
        val interceptor = HttpLoggingInterceptor()
        interceptor.level = HttpLoggingInterceptor.Level.BODY
        val client = OkHttpProvider.client.addInterceptor(interceptor).build()
        return Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(client)
            .addConverterFactory(MoshiConverterFactory.create())
            .addCallAdapterFactory(RxJava2CallAdapterFactory.createWithScheduler(Schedulers.io()))
            .build()
    }

    object OkHttpProvider {
        val client = OkHttpClient.Builder()
    }
`

I need the object for the OkHttpProvider so that it can be used for the test rule :

    class OkHttpIdlingResourceRule: TestRule {

    private val resource : IdlingResource = OkHttp3IdlingResource.create("okhttp", 
     NetworkModule.OkHttpProvider.client.build())

        override fun apply(base: Statement, description: Description): Statement {
            return object: Statement() {
                override fun evaluate() {
                    IdlingRegistry.getInstance().register(resource)
                    base.evaluate()
                    IdlingRegistry.getInstance().unregister(resource)
                }
            }
        }
    }

And in my test:

    @get:Rule
    var rule = OkHttpIdlingResourceRule()

Everything works fine until I try to add mockinizer.

    val mocks: Map<RequestFilter, MockResponse> = mapOf(

        RequestFilter("login") to MockResponse().apply {
            setResponseCode(200)
            setBody(
                """
                    {
                    "token": 1111111"
                    } 
                """.trimIndent()
            )
            setBodyDelay(1, TimeUnit.SECONDS)
            setHeadersDelay(1, TimeUnit.SECONDS)
        }
    )

When I add the .mockinize(mocks) to to the object OkHttpProvider the tests run but do not use the mock results:

        object OkHttpProvider {
            val client = OkHttpClient.Builder().mockinize(mocks)
        }

Instead, if I remove that and I add .mockinize(mocks) to the provideRetrofitInterface() I my tests fail:

        internal fun provideRetrofitInterface(): Retrofit {
            val interceptor = HttpLoggingInterceptor()
            interceptor.level = HttpLoggingInterceptor.Level.BODY
            val client = OkHttpProvider.client.addInterceptor(interceptor).mockinize(mocks).build()
            return Retrofit.Builder()
                .baseUrl(BASE_URL)
                .client(client)
                .addConverterFactory(MoshiConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.createWithScheduler(Schedulers.io()))
                .build()
        }

I get an error:

    java.net.BindException: bind failed: EADDRINUSE (Address already in use)

I think it has something to do with the rule which is why I shared the code. But I'm not sure what the issue is.

**Comment by donfuxx** [comment]
Hi @kkl260 thx for your issue report! I have some questions:

1.  Is this an open-source project where this bug happens? If so, then I could check it out try to repro the issue
2. Due you have the stacktrace of this BindException?
3. This exceptions sounds like it is trying to use a port that is already in use. The MockWebServer is using port 34567. Maybe something else is using it, or the mockserver was still running from a previous session and it is trying to start a mockserver again that is already running
4. If 3. is the case then I could just add the feature to explicitly tear down the mockserver, which you could use in tests `@After` method

**Comment by kkl260** [comment]
1. No, sorry

2 : 

        java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:109)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
        at java.net.ServerSocket.bind(ServerSocket.java:377)
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:388)
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:369)
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:359)
        at com.appham.mockinizer.MockWebServerExtKt$configure$1.invokeSuspend(MockWebServerExt.kt:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
         Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Linux.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:75)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:75)
        at libcore.io.IoBridge.bind(IoBridge.java:105)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162) 
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427) 
        at java.net.ServerSocket.bind(ServerSocket.java:377) 
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:388) 
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:369) 
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:359) 
        at com.appham.mockinizer.MockWebServerExtKt$configure$1.invokeSuspend(MockWebServerExt.kt:12) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
    
3/4 : I'm not sure, but if you're fixing it and want me to test let me know.

**Comment by donfuxx** [comment]
@kkl260 thx for the stacktrace. That's exactly what I thought: MockServer tried to start at a port that is already used.

I created a new release [1.3.0](https://github.com/donfuxx/Mockinizer/releases/tag/1.3.0) that adds some more customization possibilities:
- you can explicitly shutdown the MockWebServer when you need by using Mockinizer.shutdown()
- you can supply your own MockWebServer as a param in .mockinize() function
- you can configure custom ports that MockWebServer should use

This should give you enough flexibility to integrate Mockinizer in your tests. I created also an example androidTest with TestRules for demo purposes, see PR https://github.com/donfuxx/Mockinizer/pull/21/files

**Comment by kkl260** [comment]
Tests do not fail anymore but I'm still not getting the mock results.  I think this is something on my end but I'm wondering if you can figure out why :

In my NetworkModule class (This class is in the main project. Not in the androidTest folder): 

    @Provides
    @Reusable
    @JvmStatic
    internal fun provideRetrofitInterface(): Retrofit {
        val interceptor = HttpLoggingInterceptor()
        interceptor.level = HttpLoggingInterceptor.Level.BODY
        val client = OkHttpProvider.client.addInterceptor(interceptor).mockinize(mocks, MockWebServer()).build()
        return Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(client)
            .addConverterFactory(MoshiConverterFactory.create())
            .addCallAdapterFactory(RxJava2CallAdapterFactory.createWithScheduler(Schedulers.io()))
            .build()
    }

OkHttpIdlingResourceRule class :

    class OkHttpIdlingResourceRule: TestRule {

    private val resource : IdlingResource = OkHttp3IdlingResource.create("okhttp", NetworkModule.OkHttpProvider.client.build())

    override fun apply(base: Statement, description: Description): Statement {
        return object: Statement() {
            override fun evaluate() {
                IdlingRegistry.getInstance().register(resource)
                base.evaluate()
                IdlingRegistry.getInstance().unregister(resource)
            }
        }
    }
    }

Mocks :

val mocks: Map<RequestFilter, MockResponse> = mapOf(

    RequestFilter("login") to MockResponse().apply {
        setResponseCode(200)
        setBody(
            """
                {
                "token":"981726331f5d0dca86ea2f2fffc14260f2011111"
                } 
            """.trimIndent()
        )
        setBodyDelay(1, TimeUnit.SECONDS)
        setHeadersDelay(1, TimeUnit.SECONDS)
    }

    )

I don't really understand your tests, since they don't really interact with the UI. You're just building the mock retrofit client in your tests and making the calls from there. In reality, with a UI test, we'd want the api calls to be made based on how the app is used.

Here is an example of one of my tests:

    @Test
    fun loginWithEmailSuccess() {
        login {
            enterText(emailInput(),"email@company.com")
            enterText(passwordInput(), "12345")
            pressButton(loginButton())
        }
    }

Here, the pressButton(loginButton()) method presses the button and makes the api call. But it is currently calling our own server and not using the mock results.

**Comment by donfuxx** [comment]
Hi @kkl260 
Indeed your RequestFilter seems wrong, with:

```
RequestFilter("login")
```

your would only mock GET requests (GET is the default value, check KDoc comment in RequestFilter class :wink: ). I assume your login call is a POST request, so you are probably looking for something like:

```
RequestFilter(
     path = "login", 
     method = Method.POST
)
```

Mockinizer is picky about which requests it filters out for mocking, only if path and method matches then it would trigger a mock server response.

**Comment by kkl260** [comment]
Well, you were right. I made the change... but still not returning my mock response.

**Comment by donfuxx** [comment]
Did it instead return the real api response or did the MockWebServer return an error?

It's a bit hard to figure out the error without seeing the full project, but I stumbled upon something that doesn't seem right in your code:

```
val client = OkHttpProvider.client.addInterceptor(interceptor).mockinize(mocks, MockWebServer()).build()
```

here you are providing a custom instance of the MockWebServer, but to be able to actually return proper responses it needs to be configured before that. Mockinizer does that for you under the hood if you use the extension function MockWebServer.configure().

So I suggest you just remove the MockWebServer param in your case, as you aren't keeping a reference to it anyway (Remember that the idea was to keep a reference to the MockWebServer to be able to shut it down later when needed)

```
val client = OkHttpProvider.client.addInterceptor(interceptor).mockinize(mocks).build()
```

then after your test case is finished you can just call `Mockinizer.shutdown()` before creating new mockinized OkHttpClients.

**Comment by kkl260** [comment]
It always returns the real ai response.

The code change doesn't help. Thanks anyways.

**Comment by donfuxx** [comment]
Maybe your request is using some custom http headers? The default value for headers in RequestFilter is empty headers. If it turns out that you need to set some then you can set it in RequestFilter params, like `headers = Headers.headersOf("name", "value")` 

That's pretty much my last idea without seeing the full project that you are working on. It sure makes sense to do some debugging and add some breakpoints in MockinizerInterceptor's intercept method or RequestFilter.from method to see how the actual retrofit requests look like and to which RequestFilter instance they got mapped. Don't give up on this and let me know if you figure it out and if there is any suggestion to improve it :-)

There is also a small Mockinizer demo project, where you can see some mock responses in action, if that is of any help: https://github.com/donfuxx/MockinizerDemo

**Comment by ahmadmssm** [comment]
I'm also facing the same issue.
