### ISSUE TITLE
Mockinizer headers are added several times

### ISSUE THREAD

**Issue by JuBan1** [donfuxx/Mockinizer#24]
**Describe the bug**
Every time I query the same mocked API endpoint, a new set of headers are added to the mock response.

**To Reproduce**
Repeatedly query the same endpoint. Check the response, for example via the `HttpLoggingInterceptor` with logging level `BODY`.

**Expected Behavior**
The headers should be added only once, on creation of the MockResponse. Or the MockResponse needs to be cloned before being modified.

**More info**

![image](https://user-images.githubusercontent.com/4319621/76963918-188e3980-6922-11ea-8f56-cccdebbc6e29.png)

This is a screenshot from the debugger after I've made a few requests. As you can see, the headersBuilder contains the same set of headers 3+ times.

**Comment by donfuxx** [comment]
Good catch! Your suggestions were helpful as well.
This should be fixed with next release. 

BTW: Feel free to fork this project and open pull requests with any bugfixes / improvements that you see ;-)
