### ISSUE TITLE
Simultaneous queries can lead to the wrong responses

### ISSUE THREAD

**Issue by JuBan1** [donfuxx/Mockinizer#25]
**Describe the bug**
I have two API-Endpoints, `getA()` and `getB()` which return `ResultA` and `ResultB` respectively. Both are mocked using Mockinizer. Both Endpoints are queried at the same time. In a good number of cases the `getA()` query will end up getting the `ResultB` response, and vice versa.

My guess is that both results are intercepted by Mockinizer, the responses are enqueued into MockServer, but MockServer handles the two responses in the opposide order, leading to the wrong response being given out. 

I've verified that retrofit actually receives the wrong response by logging to json body of for the two endpoints.

**To Reproduce**
Very simply put, I have this set-up.

```java
interface TestInterface {
    @GET("/v1/a")
    suspend fun getA(): Response<ResultA>
    @GET("/v1/b")
    suspend fun getB(): Response<ResultB>
}
class Repository {
    fun loadA() {
        GlobalScope.launch {
            val resultA = retrofit.createInterface(...).getA() // sometimes fails because my mock response for getB can't be converted to ResultA
        }
    }
    fun loadB() {
        GlobalScope.launch {
            val resultB = retrofit.createInterface(...).getB() // sometimes fails because my mock response for getA can't be converted to ResultB
        }
    }
}
fun someFunction() {
    repository.loadA()
    repository.loadB()
}
```
At the moment I'm trying to understand the issue and figure out if I'm misusing something or if Mockinizer+MockServer is the culprit. I'll see if I can create a minimal test sample to showcase the problem.

In the meantime, I thought I'd ask whether you've seen issues like that previously.

PS: Perhaps to add, in the past I've used [this](https://github.com/square/okhttp/tree/master/mockwebserver#dispatcher) method to handle giving out mock responses, rather than `enqueue`. Maybe that's a good way to go.

**Comment by donfuxx** [comment]
Hi @JuBan1 parallel mocking of api responses isn't something that I have tested yet with Mockinizer. Your assumption that dispatch instead enqueue might be better for that case seem to be correct to me. I'll try that out.
Thanks for your investigation efforts!
