### ISSUE TITLE
Regression from 1.4.0: Requests with query parameters don't succeed anymore

### ISSUE THREAD

**Issue by JuBan1** [donfuxx/Mockinizer#28]
**Describe the bug**
Thanks for you work on #25. I've tested it and it seems to be resolved.

However, it seemed to have introduced a regression. I have a mock for `/path/endpoint` that usually has a query parameter associated with it. That is, the OkHttp call is addressed to `/path/endpoint?id=xyz`. This used to be ignored by Mockinizer, meaning the call got successfully mocked. 

Now, with 1.5.0, the call fails and results in a ' 404'. If I try to add a mock for `/path/endpoint?id=xyz` I'll get a `No mocks found for Request` error instead. It seems the decision whether the request should be mocked is made without taking into account the query parameters, whereas the decision *which* mock to use to done with them.

**Expected behavior**
This shows room for another enhancement of Mockinizer: being able to handle queries. I'd imagine this being done in a similar way to headers/body. E.g. one could write:

```java
// Require "id" to be exactly "1234"
RequestFilter("/path/endpoint", method = Method.GET, queries = listOf(QueryRule("id", "1234")))

// Require "id" to be set to any value
RequestFilter("/path/endpoint", method = Method.GET, queries = listOf(QueryRule("id")))

// Succeeds regardless of any query parameters set
RequestFilter("/path/endpoint", method = Method.GET)
```
I'd be willing to implement this if you agree to the syntax and behavior.

**Comment by donfuxx** [comment]
There indeed were no test cases covering scenarios that include query params!
For now I have added a fix that allows to add query params to path

**Comment by JuBan1** [comment]
Thanks again.

One remark though. Looking at the code, it seems `query?a=b&c=d` and `query?c=d&a=b` will be treated as two different calls even though they're the effectively same.

That's not a problem for me specifically, but might lead to surprises.

**Comment by donfuxx** [comment]
I have added query as a separate field now for the RequestFilter. That way it should be more flexible :+1:
